source :rubygems

gem 'nanoc'
gem 'kramdown'
gem 'adsf'
gem 'mime-types'
gem 'rubypants'
gem 'sass'
gem 'yui-compressor'
gem 'nanoc-cachebuster'
gem 'fssm'
gem 'rainpress'
gem 'yuicompressor'
gem 'nokogiri'
gem 'redcarpet'
gem 'albino'
gem 'builder'
gem 'open4'
gem 'systemu'
gem 'sinatra'
gem 'listen'
gem 'rb-fsevent', '~> 0.9'
